projectName: template-nestjs-api
namespace: seu-namespace
serviceAccount:
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::157906581678:role/multi-template-nestjs-api-prod-role
datadog:
  enabled: true
  env: prod
deployment:
  enabled: true
  labels:
    product: seu-product
    module: seu-module
  annotations:
    ad.datadoghq.com/template-nestjs-api.logs: |-
      [{
        "source": "nodejs"
      }]
  containers:
    - name: template-nestjs-api
      image:
        registry: 722447452105.dkr.ecr.us-east-1.amazonaws.com
        repository: template-nestjs-api
      readinessProbe:
        httpGet:
          path: /health
          port: 3000
        failureThreshold: 3
        initialDelaySeconds: 45
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 3000
        failureThreshold: 3
        initialDelaySeconds: 45
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 10
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: template-nestjs-api
configMaps:
  - name: template-nestjs-api
    data:
      ADDITIONAL_OPTS: ''
      PREFIX: template-nestjs-api
      DD_SERVICE: template-nestjs-api
      DD_RUNTIME_METRICS_ENABLED: 'true'
      DD_LOGS_INJECTION: 'true'
      DD_ENV: prod
      DD_PROFILING_ENABLED: 'false'
      DD_APPSEC_ENABLED: 'true'
      DD_APPSEC_SCA_ENABLED: 'true'
      DD_IAST_ENABLED: 'true'

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpuAverage: 160
  memoryAverage: 160

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: seu-namespace-private
    alb.ingress.kubernetes.io/backend-protocol: HTTP
  ingressClassName: alb
  hosts:
    - host: template-nestjs-api.k8s-multi.com.br
